### ISSUE TITLE
视频会议的语音输出可以选择使用听筒或者扬声器吗

### ISSUE THREAD

**Issue by wenyuan1104** [WildDogTeam/video-demo-android-conference#1]
你好！我们发现一个问题就是，使用了小米手机和华为手机进行视频会议。
小米手机默认使用听筒播放语音，声音就会很小。
华为手机默认使用扬声器播放语音，声音大小很OK。
请问现在sdk是否支持选择。

**Comment by wenyuan1104** [comment]
这个已经解决了

**Comment by laufly** [comment]
我们在2.3.1版本之后的SDK默认开启扬声器
