### ISSUE TITLE
偶尔崩溃

### ISSUE THREAD

**Issue by wenyuan1104** [WildDogTeam/video-demo-android-conference#2]
在使用过程中我们发现偶尔会出现崩溃问题
10-15 17:15:23.015 8991-9407/com.lzf.ydyj I/RoomClient: orangeline - onClose tryConnect invoked.
10-15 17:15:23.015 8991-9407/com.lzf.ydyj D/de.tavendo.autobahn.WebSocketConnection: WebSocket connection created.
10-15 17:15:23.016 8991-9407/com.lzf.ydyj D/RoomClient: orangeline - Start to connect websocket. wss://bt-sh-2.wilddog.com:2600/ws
10-15 17:15:23.016 8991-9410/com.lzf.ydyj D/de.tavendo.autobahn.WebSocketConnection: SocketThread exited.
10-15 17:15:23.034 8991-9638/com.lzf.ydyj W/de.tavendo.autobahn.WebSocketReader: Status: 101 (Switching Protocols)
10-15 17:15:23.034 8991-8991/com.lzf.ydyj D/de.tavendo.autobahn.WebSocketConnection: opening handshake received
10-15 17:15:23.034 8991-8991/com.lzf.ydyj D/RoomClient: orangeline - Websocket connected, onOpen event triggered.
10-15 17:15:23.037 8991-9645/com.lzf.ydyj D/RoomClient: orangeline - Sending heartbeat message : 0.
10-15 17:15:23.038 8991-9645/com.lzf.ydyj E/AndroidRuntime: FATAL EXCEPTION: Timer-3
                                                            Process: com.lzf.ydyj, PID: 8991
                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'void de.tavendo.autobahn.WebSocketWriter.forward(java.lang.Object)' on a null object reference
                                                                at de.tavendo.autobahn.WebSocketConnection.sendTextMessage(SourceFile:72)
                                                                at com.wilddog.video.room.roomclient.RoomClient$7.run(SourceFile:262)
                                                                at java.util.TimerThread.mainLoop(Timer.java:555)
                                                                at java.util.TimerThread.run(Timer.java:505)
10-15 17:15:23.040 8991-8991/com.lzf.ydyj D/RoomClient: orangeline - Text message received : ["handshake",{"sid":"idNlbJwXGC7IOa99AAba","cid":1755,"ts":1508058922226}]. 
10-15 17:15:23.040 8991-8991/com.lzf.ydyj D/RoomClient: orangeline - Sending text message : ["join",1,{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE1MDgwNTg5MDksInVzZXJfaWQiOiJjZTgxOGIyNTRhNmIzYTU3ZWFlYjYyNmY2ZDI0IiwiaXNzIjoiaHR0cHM6Ly93ZDIwODU3Nzk5NDFxcWxwcnAud2lsZGRvZ2lvLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfbnVtYmVyX3ZlcmlmaWVkIjpmYWxzZSwicHJvdmlkZXJfaWQiOiJhbm9ueW1vdXMiLCJ3aWxkZG9nIjp7ImlkZW50aXRpZXMiOnt9LCJzaWduX2luX3Byb3ZpZGVyIjoiYW5vbnltb3VzIn0sImV4cCI6MTUwODE0NTMwOX0.aapJqqBQwWYb1Ndbjldp-7RhvkaD6xFW2H06kS5aoYE","roomId":"555","appId":"wd2085779941qqlprp"}].
10-15 17:15:23.040 8991-9407/com.lzf.ydyj D/de.tavendo.autobahn.WebSocketReader: WebSocket reader created.
10-15 17:15:23.041 8991-8991/com.lzf.ydyj D/AndroidRuntime: Shutting down VM

**Comment by laufly** [comment]
这个可能是我们用的socket库存在问题,正在排查,多谢反馈!我们会尽快解决的

**Comment by laufly** [comment]
@wenyuan1104 我们已经在新版 sdk 解决这个问题,如果使用的 VideoCall SDK ,请将 SDK 更新到 2.4.0,如果是Room SDK 请将 SDK 更新到 2.2.2.
