### ISSUE TITLE
部分手机画面不能全部显示

### ISSUE THREAD

**Issue by wenyuan1104** [WildDogTeam/video-demo-android-conference#3]
你好 我们发现在华为P7和华为meta9上 画面显示不全
比如目前有五个问参加会议在两台手机上只显示一个画面或者两个画面
请问是否存在这样的问题

**Comment by laufly** [comment]
请问是否有声音,如果有声音,没有画面可能是编解码问题,升级到最新版的即可,如果声音视频都没有的话,需要一些具体的信息来辅助排查问题.
