### ISSUE TITLE
使用 androidStudio 无法打包

### ISSUE THREAD

**Issue by zhudms** [WildDogTeam/video-demo-android-conference#5]
多文件冲突,使用 AndroidStudio3.0+版本无法打包

**Comment by qiangqiang681** [comment]
demo有没有添加其他额外的依赖？有的话能否贴出来？另外有没有详细错误日志？

**Comment by qiangqiang681** [comment]
@zhudms demo有没有添加其他额外的依赖？有的话能否贴出来？另外有没有详细错误日志？
